# Курс по нейронным сетям
### Первичный notebook, установка numpy, pandas и все такое

### Массивы в NumPy

In [1]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])  # создаём массив
print(a)  # смотрим на массив

[[1 2 3]
 [4 5 6]]


In [2]:
a.shape  # смотрим на форму массива

(2, 3)

Для n-мерных массивов соответствующим образом определены основные арифметические и логические операции (+ - * / // % ** < <= == >= > != выполняются поэлементно, если вторым аргументом бинарной операции указано число (скаляр), то он преобразуется в массив той же формы, что и первый аргумент). Также для n-мерных массивов реализованы все основные методы, которые могут понадобиться при работе (дальше мы покажем те из них, которые будут особенно нужны при решении заданий курса).

**Как создать массив:**

**array(object)** — n-мерный массив из любой (возможно, вложенной) последовательности,<br>
**eye(N, M=N, k=0)** -- двумерный массив с N строками с единицами на диагонали и нулями во всех остальных позициях. Число столбцов M по умолчанию равно N, k — сдвиг диагонали (0 для основной диагонали, положительные числа для верхних диагоналей и отрицательные для нижних),<br>
**zeros(shape)** -- новый массив указанной формы, заполненный нулями,<br>
**ones(shape)** -- новый массив указанной формы, заполненный единицами,<br>
**full(shape, fill_value)** -- новый массив указанной формы, заполненный fill_value.

In [3]:
print(np.eye(5, 3, k=-1))

[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


In [4]:
print(np.array([[1,2,3], [4,5,6]])) # матрица формы (2, 3) из последовательности последовательностей

[[1 2 3]
 [4 5 6]]


**Как получить доступ к элементу массива или выбрать кусок массива:**

* в NumPy используется стандартное  выделение подмножеств: **a[start:stop:step]** выбирает элементы из a с индексами от start до stop с шагом step, т.е. a[start], a[start + step], a[start + 2*step] и так далее, пока индексы меньше stop; при step = 1 этот параметр можно опустить, оставив start:stop, при start, равном минимальному индексу в массиве, или stop, равному максимальному индексу, эти индексы также можно опустить: это будет выглядеть как a[:];<br>
* отрицательные индексы;<br>
* поддерживается синтаксис многоточия: a[..., 1] выбирает элементы с любым индексом в первом измерении и с индексом, равным 1, во втором измерении:  a[:, 1] оказывается эквивалентно a[..., 1];<br>
* можно указать индексы сразу в нескольких измерениях, указав их через запятую в квадратных скобках (как a[..., 1] в примере выше).

### Создайте и напечатайте (с помощью функции print) массив класса np.ndarray ширины 4 и высоты 3 с двойками на главной диагонали и единицами на первой диагонали над главной

In [23]:
massiv = np.eye(3, 4)*2 + np.eye(3,4,k=1)
print(massiv)

[[ 2.  1.  0.  0.]
 [ 0.  2.  1.  0.]
 [ 0.  0.  2.  1.]]


### Основные методы ndarray
Для работы с многомерными массивами в NumPy реализованы самые часто требующиеся операции. Некоторые из них (которые особенно часто будут нужны в нашем курсе) мы сейчас покажем.

**Форма массива**<br>
* `a.flatten()` — превращает массив в одномерный.
* `a.T` или `a.transpose(*axes)` — транспонирование (или смена порядка осей в случае, когда размерность массива больше двух).
* `a.reshape(shape)` — смена формы массива. Массив "распрямляется" и построчно заполняется в новую форму.

In [24]:
import random
w = np.array(random.sample(range(1000), 12)) # одномерный массив из 12 случайных чисел от 1 до 1000
w = w.reshape((2,2,3)) # превратим w в трёхмерную матрицу
print(w)

[[[338 433 979]
  [195 594 377]]

 [[857 898 116]
  [ 66  56 579]]]


In [25]:
print(w.transpose(0,2,1))

[[[338 195]
  [433 594]
  [979 377]]

 [[857  66]
  [898  56]
  [116 579]]]


### Массив, который нужно было создать в предыдущей задаче, хранится в переменной mat. Превратите его в вертикальный вектор и напечатайте.

In [27]:
mat = np.eye(3, 4)*2 + np.eye(3,4,k=1)
mat_flat = mat.reshape(12,1)
print(mat_flat)

[[ 2.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 1.]]


### Основные методы ndarray
**Базовые статистики** <br>
* `a.min(axis=None)`, `a.max(axis=None)`, `a.mean(axis=None)`, `a.std(axis=None)` — минимум, максимум, среднее арифметическое и стандартное отклонение вдоль указанной оси. По умолчанию ось не указана и статистика считается по всему массиву. `a.argmin(axis=None)`, `a.argmax(axis=None)` — индексы минимального и максимального элемента. Пример:

In [29]:
print(mat)

[[ 2.  1.  0.  0.]
 [ 0.  2.  1.  0.]
 [ 0.  0.  2.  1.]]


In [31]:
print(mat.mean(axis=0))  # вдоль столбцов

[ 0.66666667  1.          1.          0.33333333]


In [33]:
print(mat.mean(axis=1))  # вдоль строк

[ 0.75  0.75  0.75]


In [35]:
print(mat.mean(axis=None))  # вдоль всего массива

0.75


Чтобы лучше понять, почему говорят «усреднение вдоль оси» — можно нарисовать эту матрицу на бумажке и прямыми линиями соединить те элементы, которые сливаются в один при усреднении. Чтобы было совсем понятно — можно ещё добавить координатные оси, чтобы каждый элемент wijwij оказался над точкой (i,j).
* `a.sum(axis=None)`, `a.prod(axis=None)` — сумма и произведение всех элементов вдоль указанной оси. `a.cumsum(axis=None)`, `a.cumprod(axis=None)` — частичные суммы и произведения (для (a1,⋯,an) вектор частичных сумм — это (a1,a1+a2,⋯,a1+⋯+an)(a1,a1+a2,⋯,a1+⋯+an)).

### Линейная алгебра
Пакет numpy.linalg содержит большую часть стандартных операций и разложений матриц. Некоторые самые популярные функции вынесены в корень пакета NumPy.
* a.dot(b) — матричное произведение двух массивов (размерности должны быть согласованы)
* linalg.matrix_power(M, n) — возведение матрицы M в степень n
* a.T — транспонирование
* linalg.norm(a, ord=None) — норма матрицы a, по умолчанию норма Фробениуса для матриц и L2-норма для векторов; подробное описание возможных норм — в [справке](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html#numpy.linalg.norm/)
* linalg.inv(a) — матрица, обратная к a (если a необратима, выбрасывается LinAlgError; псевдообратная считается через linalg.pinv(a))

In [36]:
a = w.dot([1,2,3])
print(a)

[[4141 2514]
 [3001 1915]]


In [37]:
ainv = np.linalg.inv(a)
print(a.dot(ainv))

[[  1.00000000e+00   0.00000000e+00]
 [ -1.77635684e-15   1.00000000e+00]]


Подробные описания с указанием полного списка аргументов, а также описания всех остальных функций находятся на сайте проекта [NumPy](http://docs.scipy.org/doc/numpy/reference/index.html/).

### Перемножение матриц
На вход программе подаются две матрицы, каждая в следующем формате: на первой строке два целых положительных числа $n$ и $m$, разделенных пробелом - размерность матрицы. В следующей строке находится $n*m$ целых чисел, разделенных пробелами - элементы матрицы. Подразумевается, что матрица заполняется построчно, то есть первые m чисел - первый ряд матрицы, числа от $m+1$ до $2*m$ - второй, и т.д.<br>
Напечатайте произведение матриц $XY^T$, если они имеют подходящую форму, или строку "matrix shapes do not match", если формы матриц не совпадают должным образом. 

* `map(f, iterable, …)` — встроенная функция языка Python, возвращает результат поэлементного применения функции f к элементам последовательности `iterable`; если f принимает несколько аргументов, то на вход должно быть подано соответствующее число последовательностей: результатом `map(f, x, y, z)` будет итератор, возвращающий поочерёдно `f(x[0], y[0], z[0]), f(x[1], y[1], z[1]), f(x[2], y[2], z[2])` и так далее; результат применения f к очередному набору аргументов вычисляется только тогда, когда требуется использовать этот результат, но не ранее, подробнее и короче в справке;
* `np.fromiter` создаёт NumPy-массив из итератора, то есть заставляет итератор вычислить все доступные значения и сохраняет их в массив;

In [39]:
x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int,input().split()), np.int).reshape(y_shape)

try:
    C = X.dot(Y.T)
    print(C)
except ValueError:
    print("matrix shapes do not match")

2 3
5 9 9 10 8 9
3 4
6 11 3 5 4 5 3 2 5 8 2 2
matrix shapes do not match


### Как считать данные из файла
```python
>>> sbux = np.loadtxt("sbux.csv", usecols=(0,1,4), skiprows=1, delimiter=",", 
                      dtype={'names': ('date', 'open', 'close'),
                             'formats': ('datetime64[D]', 'f4', 'f4')})
>>> print(sbux[0:4])
[(datetime.date(2015, 9, 1), 53.0, 57.2599983215332)
 (datetime.date(2015, 8, 3), 58.619998931884766, 54.709999084472656)
 (datetime.date(2015, 7, 1), 53.86000061035156, 57.93000030517578)
 (datetime.date(2015, 6, 1), 51.959999084472656, 53.619998931884766)]
```
`"sbux.csv"` — имя файла (или сюда же можно передать объект файла, такой пример вы увидите в следующей задаче урока), из которого считываются данные.<br>
`usecols` — список колонок, которые нужно использовать. Если параметр не указан, считываются все колонки.<br>
`skiprows` — количество рядов в начале файла, которые нужно пропустить. В нашем случае пропущен ряд заголовков. По умолчанию (если значение параметра не указано явно) skiprows = 0.<br>
`delimiter` — разделитель столбцов в одной строке, в csv-файлах это запятая, по умолчанию разделителем является любой пробел (в том числе — знак табуляции).<br>
`dtype` — словарь из названий колонок (переменных) и типов хранящихся в них значений. NumPy использует свою собственную систему типов, и названия именно этих типов нужно указать. По умолчанию функция попытается самостоятельно угадать, какому типу принадлежат подаваемые на вход значения.

**Задача: считайте данные из файла и посчитайте их средние значения.**
На вход вашему решению будет подан адрес, по которому расположен csv-файл, из которого нужно считать данные. Первая строчка в файле — названия столбцов, остальные строки — числовые данные (то есть каждая строка, кроме первой, состоит из последовательности вещественных чисел, разделённых запятыми).

Посчитайте и напечатайте вектор из средних значений вдоль столбцов входных данных.

In [51]:
from urllib.request import urlopen
f = urlopen('https://stepic.org/media/attachments/lesson/16462/boston_houses.csv')
#Теперь в f содержится объект файла, который можно передать в loadtxt.
dataset = np.loadtxt(f, skiprows=1, delimiter=',')
#Теперь расчеты
col_means = dataset.mean(axis=0)  # вдоль столбцов
print(col_means)

[ 22.53280632   3.61352356  11.36363636   0.06916996   0.55469506
   6.28463439   3.79504269]


In [50]:
dataset[1][0]

21.600000000000001